#This file (config.properties) stores the information that remains static throughout the framework such as browser 
#specific information, application URL, screenshots path etc,
#
#i.e., All Page URLs, WebDriver File Paths(geckodriver, FirefoxDriver, InternetExplorer), 
#Test Input Data, Test Output Data & Error Screenshots will be maintained.

geckoDriver=C:/Users/Satish Kumar M/eclipse-workspace/DDT_Framework_TestProject/Resources/geckodriver.exe
chromeDriver=C:/Users/Satish Kumar M/eclipse-workspace/DDT_Framework_TestProject/Resources/chromedriver.exe
url=https://wellsoffice.ceo.wellsfargo.com/
testInputData=C:/Users/Satish Kumar M/eclipse-workspace/DDT_Framework_TestProject/Configuration/TestData.xml
Failedscreenshots_Path=C:/Users/SatishKumarM/eclipse-workspace/DDT_Framework_TestProject/FailedScreenshots